src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    #[Assert\GreaterThanOrEqual("today")]
    private $dt_heure_depart;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    #[Assert\GreaterThan(propertyPath: "dt_heure_depart")] // Permet d'éviter d'avoir des dates négatives 
    private $dt_heure_fin;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value:30)]
    private $prix_total;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $dt_enregistrement;

    #[ORM\ManyToOne(targetEntity:Vehicule::class, inversedBy:"commandes", cascade:["persist"])]
    private $vehicule;

    #[ORM\ManyToOne(targetEntity:User::class, inversedBy:"commandes", cascade:["persist"])]
    private $user;

    public function __construct(){

        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);
        $this->setDtEnregistrement($now); 

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDtHeureDepart(): ?\DateTimeInterface
    {
        return $this->dt_heure_depart;
    }

    public function setDtHeureDepart(\DateTimeInterface $dt_heure_depart): self
    {
        $this->dt_heure_depart = $dt_heure_depart;

        return $this;
    }

    public function getDtHeureFin(): ?\DateTimeInterface
    {
        return $this->dt_heure_fin;
    }

    public function setDtHeureFin(\DateTimeInterface $dt_heure_fin): self
    {
        $this->dt_heure_fin = $dt_heure_fin;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getDtEnregistrement(): ?\DateTimeInterface
    {
        return $this->dt_enregistrement;
    }

    public function setDtEnregistrement(\DateTimeInterface $dt_enregistrement): self
    {
        $this->dt_enregistrement = $dt_enregistrement;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use App\Entity\User;
use App\Entity\Vehicule;
use App\Twig\FiltreExtension;
use DateTime;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{

    public function __construct(private FiltreExtension $filter){

    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dt_heure_depart', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'min' => (new DateTime())->format('Y-m-d H:i:s'), // Permet d'empêcher de sélectionner une date antérieur au jour même
            
                ]
            ])
            ->add('dt_heure_fin', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'min' => (new DateTime())->format('Y-m-d H:i:s') 
                ]
            ])
            ->add('vehicule', EntityType::class, [
                'class' => Vehicule::class,
                //'choice_label' => 'titre',
                'choice_label' => function ($vehicule){
                    return $vehicule->getTitre() . " - " . $this->filter->deviseFR($vehicule->getPrixJournalier());
                }
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'pseudo',
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Vehicule;
use App\Form\CommandeType;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CommandeController extends AbstractController
{

    #[Route("/liste/commande", name: "list_commande")]
    public function liste(ManagerRegistry $doctrine)
    {
        $commandes = $doctrine->getRepository(Commande::class)->findAll();
        return $this->render("commande/list-commandes.html.twig", compact("commandes"));
    }


    /**
     * Il est possible d'associer plusieurs routes à une seule méthode
     * Pratique pour le new et update qui ont presque le même code
     */

    #[Route("/new/commande", name: "form_commande")]
    #[Route("/update/{id}", name: "commande_update")]
    public function new_commande(Request $request, EntityManagerInterface $em, Commande $commande = null): Response
    {

        // Si on appelle new alors la commande est null puisque pas d'id, donc nouveau formulaire mais si on appelle {id} -> alors formulaire prè rempli
        if($commande == null){ 
            $commande = new Commande();
            $commande->setDtHeureDepart(new DateTime())
                    ->setDtHeureFin(NEW DateTime());
        }
       
        $form = $this->createForm(CommandeType::class, $commande);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // Récupérer dt_debut / dt_fin 
            $dt_debut = $form->get("dt_heure_depart")->getData();
            $dt_fin = $form->get("dt_heure_fin")->getData();
            $interval = $dt_debut->diff($dt_fin);
            $interval->format("%r%a");
            $nbJours = $interval->days;

            if($nbJours < 1){
                $this->addFlash("message", "Une réservation doit durer au minimum 24h !");
            }

            // Vérification de la disponibilité des véhicule

            $listeVehiculeLoue = $em->getRepository(Commande::class)->listeVehiculeLoue($dt_debut, $dt_fin);
            $vehicule = $form->get("vehicule")->getData();
            if(in_array($vehicule->getId(),  $listeVehiculeLoue)){
                $listeVehiculeDispo = $em->getRepository(Vehicule::class)->findByVehiculeDisponibles($listeVehiculeLoue);
                $this->addFlash("message", "Le véhicule demandé est déjà reservé pour cette période !");
                $this->addFlash("vehicules", ["disponibles" => $listeVehiculeDispo]);
            }
           

            // Récupérer le prix selon le véhicule choisi 
            
            if(!in_array($vehicule->getId(), $listeVehiculeLoue) && $nbJours >= 1){

                $prixJournalier = $vehicule->getPrixJournalier();

                // Multiplication = nb_jour * prix_journalier
                $commande->setPrixTotal($nbJours * $prixJournalier);
    
                $em->persist($commande);
                $em->flush();
                return $this->redirectToRoute("list_commande");
            }
           
        }
        return $this->render("commande/form-commande.html.twig", ["form" => $form->createView(),
                                                                    "id" => $commande->getId()]);
    }

    
    // ParamConverter
    #[Route("/delete/{id}", name: "commande_delete")]
    public function delete(Commande $commande, EntityManagerInterface $em): Response{

        

        if ($commande === null) {
            return $this->redirectToRoute("list_commande");
        }

        if ($commande) {
            $em->remove($commande);
            $em->flush();
            return $this->redirectToRoute("list_commande");
        }
    }
}

templates/commande/form-commande.html.twig
{% extends 'back-office.html.twig' %}

{% block title %}Commandes
{% endblock %}

{% block body %}
	<h1 class="text-center">
		{{ id ? "Modifier la commande numéro " ~ id : "Créer une nouvelle commande"}}
	</h1>

	{% for message in app.flashes("message")%}
		<div class="alert alert-danger">
			{{ message}}
		</div>
	{% endfor %}
	{% for vehicule in app.flashes("vehicules")%}
		<div class="alert alert-info">
			<div>Liste des véhicules disponibles sur le créneau demandé</div>

			<ul>
				{% for v in vehicule.disponibles %}
					<li> {{ v.titre }} </li>
                    {% else %}
                    <li>Aucun véhicule en stock sur cette période</li>
				{% endfor %}
			</ul>
		</div>
	{% endfor %}
	{{ form(form) }}{% endblock %}

templates/commande/list-commandes.html.twig
{% extends "back-office.html.twig" %}

{% block titre %}Liste des commandes {% endblock %}

{% block body %}
<main class="row">
    <h1 class="text-center">Liste des commandes</h1>
       <table class="table table-dark m-5">
  <thead>
    <tr class="text-center">
        <th style="width:5%">Numéro de commande</th>
         <th style="width:10%">Véhicule</th>
         <th style="width:20%">Utilisateur</th>
         <th style="width:10%">Date de départ</th>
         <th style="width:10%">Date de retour</th>
         <th style="width:10%">Prix total</th>
         <th style="width:10%">Date d'enregistrement</th>
         <th style="width:20%">Options</th>
    </tr>
  </thead>
  <tbody>
    {% for commande in commandes %}
    <tr>
         <td class="text-center">{{ commande.id }}</td>
         <td class="text-center">{{ commande.vehicule.id }} - {{ commande.vehicule.titre }}</td> 
          <td class="text-center">{{ commande.user.id }} - {{ commande.user.pseudo }}</td>
          <td class="text-center">{{ commande.dtHeureDepart | date("d/m/Y H:i:s")  }}</td>
          <td class="text-center">{{ commande.dtHeureFin | date("d/m/Y H:i:s") }}</td> 
          <td class="text-center"> {{commande.prixTotal | deviseFr }} </td>   
          <td class="text-center">{{ commande.dtEnregistrement | date("d/m/Y H:i:s") }}</td> 
    

      <td> 
    {% include "commun/actions.html.twig" with {"id" : commande.id, "update" : "commande_update", "delete" : "commande_delete" } %}
            
       </td>   
    </tr>
    {% endfor %}
</main>
{% endblock %}