src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3, max:200)]
    private $titre;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3, max:50)]
    private $marque;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\Length(min:3, max:50)]
    private $modele;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 200)]
    #[Assert\Length(min:3)]
    private $photo;

    #[ORM\Column(type: 'integer')]
    #[Assert\GreaterThan(value: 30)]
    private $prix_journalier;

    #[ORM\Column(type: 'datetime')]
    #[Assert\Type("datetime")]
    private $dt_enregistrement;

    #[ORM\OneToMany(targetEntity:Commande::class, mappedBy:"vehicule")]
    private $commandes;

    public function __construct(){

        $tz = new \DateTimeZone('Europe/Paris');
        $now = new \DateTime();
        $now->setTimezone($tz);
        $this->setDtEnregistrement($now);
        $this->commandes = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDtEnregistrement(): ?\DateTimeInterface
    {
        return $this->dt_enregistrement;
    }

    public function setDtEnregistrement(\DateTimeInterface $dt_enregistrement): self
    {
        $this->dt_enregistrement = $dt_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

templates/front/commande.html.twig
{% extends "front.html.twig" %}

{% block title %}Synthèse{% endblock %}


{% block body %}
<h2>Finaliser votre location</h2>
{{form(form)}}

{% endblock %}

templates/front/index.html.twig
{% extends "front.html.twig" %}

{% block title %}
	Page d'accueil
{% endblock %}

{% block body %}

	<div class="d-flex justify-content-center m-5">


		<form action="{{ path("home_search")}}" method="POST"></form>
		<label for="dt_debut">Départ</label>
		<input type="datetime-local" name="dt_debut" id="dt_debut">

		<label for="dt_fin">Départ</label>
		<input type="datetime-local" name="dt_fin" id="dt_fin">

		<input type="submit" value="Rechercher">
	</div>


{% endblock %}

templates/front/resultats.html.twig
{% extends "front.html.twig" %}

{% block title %}Liste des véhicules disponibles{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        {% include "commun/form-search.html.twig" %}
    </div>
    <h1 class="text-center">Liste des véhicules disponibles</h1>
            {%  for vehicule in vehicules %}
                <article class="row">
                    <figure class="offset-3 col-3">
                        <img src="/upload{{ asset(vehicule.photo)}}" alt="" class="img-fluid img-thumbnail border-dark">
                    </figure>
                    <div class="col-3">
                        <h2>{{vehicule.titre}}</h2>
                        <p>{{vehicule.prixJournalier | deviseFr}}</p>
                        <p>{{vehicule.description}}</p>
                        <a href="{{ path("home_rent" , {"id" : vehicule.id }) }}" class="btn btn-primary">Louer </a>
                    </div>
                </article>
            {% else %}
                <p class="alert alert-danger">aucun véhicule enregistré pour le moment</p>
            {% endfor %}
{% endblock %}